#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

sudo apt-get update
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Configure HAProxy frontend and backend
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOF

frontend 7025_frontend
    bind *:80
    default_backend 7025_backend

backend 7025_backend
    balance roundrobin
    server 7025-web-01 44.203.48.14:80 check
    server 7025-web-02 44.203.119.237:80 check
EOF

sudo service haproxy restart